version: '3.8'

services:
  # PostgreSQL Database with PGVector extension
  postgres:
    image: pgvector/pgvector:pg16
    container_name: devforge-postgres-dev
    environment:
      POSTGRES_DB: devforge
      POSTGRES_USER: devforge
      POSTGRES_PASSWORD: devforge_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - devforge-dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devforge"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Redis for caching and real-time features
  redis:
    image: redis:7-alpine
    container_name: devforge-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    networks:
      - devforge-dev
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    restart: unless-stopped

  # Optional: Database Admin Interface
  adminer:
    image: adminer:latest
    container_name: devforge-adminer-dev
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    networks:
      - devforge-dev
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data_dev:
  redis_data_dev:

networks:
  devforge-dev:
    driver: bridge
