version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: devforge-postgres-prod
    environment:
      POSTGRES_DB: devforge
      POSTGRES_USER: devforge
      POSTGRES_PASSWORD: devforge_password
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - devforge-prod
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devforge"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: devforge-redis-prod
    command: redis-server --appendonly yes
    volumes:
      - redis_data_prod:/data
    networks:
      - devforge-prod
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    container_name: devforge-web-prod
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://devforge:devforge_password@postgres:5432/devforge
      - REDIS_URL=redis://redis:6379
      - NEXTAUTH_URL=https://${DOMAIN}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-change-me}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - devforge-prod
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  caddy:
    image: caddy:2-alpine
    container_name: devforge-caddy
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN=${DOMAIN}
      - CADDY_EMAIL=${CADDY_EMAIL:-devnull@example.com}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    depends_on:
      - web
    networks:
      - devforge-prod
    restart: unless-stopped

volumes:
  postgres_data_prod:
  redis_data_prod:
  caddy_data:
  caddy_config:

networks:
  devforge-prod:
    driver: bridge


